In [1]:
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt

In [2]:
dgis = pd.read_csv("dgis_info.csv")
iter_final = pd.read_csv("./iter_interpolado.csv")
pobreza_final = pd.read_csv("./pobreza_municipal_clean_interpolado.csv")

#dgis.head
dgis[dgis["año"] == 2015]

,clave_municipio,año,hombres_dmt1_sin_esc,hombres_dmt1_preescolar,hombres_dmt1_primaria,hombres_dmt1_secundaria,hombres_dmt1_preparatoria,hombres_dmt1_profesional,hombres_dmt1_posgrado,hombres_dmt2_sin_esc,...,15-24_sexo2_dmt2,25-59_sexo1_dmt1,25-59_sexo1_dmt2,25-59_sexo2_dmt1,25-59_sexo2_dmt2,60+_sexo1_dmt1,60+_sexo1_dmt2,60+_sexo2_dmt1,60+_sexo2_dmt2,casos totales
0,2,2015,0,0,1,0,1,1,0,5,...,0,2,63,3,27,1,170,2,164,432
1,3,2015,0,0,4,3,0,1,0,6,...,0,2,56,2,24,6,182,3,226,501
2,4,2015,0,0,1,0,0,0,0,4,...,0,0,11,0,8,1,37,2,36,96
3,5,2015,0,0,3,2,5,0,0,25,...,1,5,167,4,94,5,444,7,499,1227
4,6,2015,0,0,1,1,0,0,0,6,...,0,1,61,0,39,1,161,2,183,448
5,7,2015,1,0,7,5,3,1,0,49,...,0,8,241,5,141,8,507,7,571,1490
6,8,2015,0,0,1,0,0,0,0,6,...,0,0,21,0,19,1,62,1,62,166
7,9,2015,0,0,0,0,0,0,0,7,...,0,0,22,0,14,0,47,0,53,136
8,10,2015,0,0,3,0,1,0,0,20,...,1,2,71,1,54,1,196,4,219,551
9,11,2015,0,0,1,1,2,0,0,6,...,0,2,45,0,26,1,84,1,115,275
10,12,2015,0,0,1,3,2,1,0,20,...,0,3,82,1,35,3,157,2,153,437
11,13,2015,0,0,1,1,3,2,0,11,...,0,4,49,1,31,3,109,2,128,327
12,14,2015,0,0,0,1,0,1,0,0,...,0,1,28,1,16,1,93,2,116,258
13,15,2015,0,0,2,3,2,2,1,6,...,0,4,67,0,42,5,204,5,202,530
14,16,2015,0,0,1,1,3,1,0,7,...,0,3,39,2,23,3,115,2,108,295
15,17,2015,0,0,1,3,0,1,0,6,...,0,1,69,2,27,3,152,2,187,445

In [3]:
iter_final[iter_final["año"] == 2015]

,año,mun,nom_mun,pobtot,pobmas,pobfem,p15ym_an_m,p15ym_an_f,p15ym_se,p15ym_se_m,...,p_15a24,p_15a24_m,p_15a24_f,p_25a59,p_25a59_m,p_25a59_f,p_60ymas,p_60ymas_m,p_60ymas_f,p15ym_an
0,2015,2.0,Azcapotzalco,423458.0,200502.0,222956.0,1146.0,3309.0,5987.0,1766.0,...,62771.0,31613.0,31158.0,224526.0,105717.0,118809.0,67567.0,28269.0,39298.0,4455.0
6,2015,14.0,Benito Juárez,409796.0,189266.0,220530.0,374.0,1158.0,2498.0,722.0,...,45441.0,22423.0,23018.0,243770.0,114418.0,129352.0,73976.0,28774.0,45202.0,1531.0
12,2015,3.0,Coyoacán,617432.0,290800.0,326631.0,1984.0,4615.0,9292.0,3102.0,...,91242.0,45722.0,45520.0,326470.0,152777.0,173692.0,106930.0,45076.0,61854.0,6600.0
18,2015,4.0,Cuajimalpa de Morelos,202038.0,96396.0,105643.0,908.0,1963.0,4113.0,1444.0,...,34450.0,16603.0,17848.0,105843.0,49629.0,56214.0,20008.0,8947.0,11060.0,2872.0
24,2015,15.0,Cuauhtémoc,538858.0,256338.0,282520.0,1324.0,3829.0,7108.0,2085.0,...,75754.0,37980.0,37774.0,299791.0,143869.0,155922.0,81686.0,33174.0,48512.0,5152.0
30,2015,5.0,Gustavo A. Madero,1179562.0,567554.0,612008.0,4934.0,12178.0,26228.0,10714.0,...,187221.0,95050.0,92172.0,604802.0,290171.0,314630.0,175970.0,75154.0,100816.0,17112.0
36,2015,6.0,Iztacalco,394510.0,187443.0,207068.0,1256.0,3303.0,6276.0,1972.0,...,60332.0,30380.0,29952.0,206174.0,97476.0,108699.0,60570.0,25476.0,35094.0,4560.0
42,2015,7.0,Iztapalapa,1825636.0,884324.0,941312.0,9708.0,22332.0,46648.0,18950.0,...,309698.0,155980.0,153718.0,934854.0,448036.0,486817.0,213898.0,94054.0,119843.0,32040.0
48,2015,8.0,La Magdalena Contreras,243354.0,116390.0,126964.0,1322.0,2880.0,6558.0,2373.0,...,40120.0,20081.0,20038.0,124732.0,58936.0,65796.0,31176.0,13420.0,17757.0,4202.0
54,2015,16.0,Miguel Hidalgo,393680.0,184067.0,209612.0,755.0,2254.0,4780.0,1408.0,...,50984.0,24699.0,26284.0,221672.0,104044.0,117629.0,60825.0,24796.0,36029.0,3010.0
60,2015,9.0,Milpa Alta,141634.0,69282.0,72352.0,1233.0,2242.0,3796.0,1460.0,...,25926.0,13098.0,12828.0,69358.0,33180.0,36178.0,13076.0,6108.0,6968.0,3474.0
66,2015,12.0,Tlalpan,675248.0,323508.0,351740.0,3196.0,6800.0,15032.0,5450.0,...,111364.0,56054.0,55310.0,351342.0,165798.0,185544.0,87501.0,38113.0,49388.0,9996.0
72,2015,11.0,Tláhuac,376289.0,182700.0,193589.0,1828.0,3930.0,7367.0,2612.0,...,66238.0,33420.0,32818.0,191970.0,91277.0,100694.0,36576.0,16461.0,20114.0,5757.0
78,2015,0.0,Total de la entidad Ciudad de México,9030512.0,4319355.0,4711157.0,37010.0,86812.0,177434.0,64956.0,...,1420885.0,712896.0,707990.0,4740720.0,2252866.0,2487854.0,1247634.0,530983.0,716650.0,123822.0
84,2015,17.0,Venustiano Carranza,437341.0,206884.0,230456.0,1306.0,3252.0,6166.0,1939.0,...,66200.0,33284.0,32916.0,227998.0,107453.0,120544.0,68020.0,28062.0,39958.0,4558.0
90,2015,13.0,Xochimilco,428592.0,210378.0,218214.0,2562.0,5070.0,9472.0,3584.0,...,73622.0,37454.0,36168.0,219922.0,107346.0,112575.0,49192.0,21952.0,27240.0,7632.0
96,2015,10.0,Álvaro Obregón,743086.0,353524.0,389562.0,3174.0,7697.0,16115.0,5374.0,...,119523.0,59056.0,60468.0,387496.0,182739.0,204757.0,100664.0,43148.0,57516.0,10871.0

In [4]:
iter_final = iter_final.rename(columns={"mun": "clave_municipio"})
iter_final

,año,clave_municipio,nom_mun,pobtot,pobmas,pobfem,p15ym_an_m,p15ym_an_f,p15ym_se,p15ym_se_m,...,p_15a24,p_15a24_m,p_15a24_f,p_25a59,p_25a59_m,p_25a59_f,p_60ymas,p_60ymas_m,p_60ymas_f,p15ym_an
0,2015,2.0,Azcapotzalco,423458.0,200502.0,222956.0,1146.0,3309.0,5987.0,1766.0,...,62771.0,31613.0,31158.0,224526.0,105717.0,118809.0,67567.0,28269.0,39298.0,4455.0
1,2016,2.0,Azcapotzalco,425207.0,201391.0,223816.0,1120.0,3179.0,5762.0,1711.0,...,62105.0,31324.0,30781.0,224298.0,105684.0,118614.0,69784.0,29232.0,40551.0,4299.0
2,2017,2.0,Azcapotzalco,426957.0,202281.0,224676.0,1094.0,3049.0,5537.0,1655.0,...,61438.0,31035.0,30404.0,224070.0,105651.0,118418.0,72000.0,30195.0,41805.0,4143.0
3,2018,2.0,Azcapotzalco,428706.0,203171.0,225536.0,1069.0,2918.0,5313.0,1600.0,...,60772.0,30745.0,30026.0,223841.0,105619.0,118223.0,74217.0,31159.0,43058.0,3987.0
4,2019,2.0,Azcapotzalco,430456.0,204060.0,226395.0,1043.0,2788.0,5088.0,1544.0,...,60105.0,30456.0,29649.0,223613.0,105586.0,118027.0,76433.0,32122.0,44312.0,3831.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2016,10.0,Álvaro Obregón,746296.0,355021.0,391275.0,3143.0,7505.0,15816.0,5317.0,...,118576.0,58738.0,59838.0,387028.0,182523.0,204505.0,104995.0,45062.0,59933.0,10648.0
98,2017,10.0,Álvaro Obregón,749506.0,356517.0,392989.0,3111.0,7314.0,15517.0,5260.0,...,117629.0,58421.0,59208.0,386559.0,182306.0,204253.0,109326.0,46976.0,62350.0,10425.0
99,2018,10.0,Álvaro Obregón,752716.0,358014.0,394703.0,3080.0,7122.0,15219.0,5203.0,...,116683.0,58104.0,58579.0,386091.0,182090.0,204001.0,113657.0,48889.0,64767.0,10202.0
100,2019,10.0,Álvaro Obregón,755927.0,359510.0,396416.0,3048.0,6931.0,14920.0,5145.0,...,115736.0,57786.0,57950.0,385622.0,181873.0,203749.0,117988.0,50803.0,67185.0,9979.0
101,2020,10.0,Álvaro Obregón,759137.0,361007.0,398130.0,3017.0,6739.0,14621.0,5088.0,...,114789.0,57469.0,57320.0,385154.0,181657.0,203497.0,122319.0,52717.0,69602.0,9756.0

In [5]:
pobreza_final = pobreza_final[pobreza_final["año"] >= 2015]
pobreza_final

,año,clave_municipio,municipio,pobreza_porcentaje,pobreza_poblacion,pobreza_extrema_porcentaje,pobreza_extrema_poblacion,pobreza_moderada_porcentaje,pobreza_moderada_poblacion
5,2015,2.0,Azcapotzalco,19.50,77859.0,0.5,2132.0,18.90,75727.0
6,2016,2.0,Azcapotzalco,20.44,81876.0,0.9,3704.0,19.46,78172.0
7,2017,2.0,Azcapotzalco,21.38,85893.0,1.3,5275.0,20.02,80617.0
8,2018,2.0,Azcapotzalco,22.32,89909.0,1.7,6847.0,20.58,83063.0
9,2019,2.0,Azcapotzalco,23.26,93926.0,2.1,8418.0,21.14,85508.0
...,...,...,...,...,...,...,...,...,...
171,2016,10.0,Álvaro Obregón,29.86,221682.0,2.0,14610.0,27.86,207073.0
172,2017,10.0,Álvaro Obregón,31.82,234676.0,2.9,21197.0,28.92,213479.0
173,2018,10.0,Álvaro Obregón,33.78,247669.0,3.8,27784.0,29.98,219886.0
174,2019,10.0,Álvaro Obregón,35.74,260663.0,4.7,34371.0,31.04,226292.0
175,2020,10.0,Álvaro Obregón,37.70,273656.0,5.6,40958.0,32.10,232699.0

In [6]:
union = pd.merge(iter_final, dgis, on=["año", "clave_municipio"], how="outer")
union.columns

Index(['año', 'clave_municipio', 'nom_mun', 'pobtot', 'pobmas', 'pobfem',
       'p15ym_an_m', 'p15ym_an_f', 'p15ym_se', 'p15ym_se_m', 'p15ym_se_f',
       'p15pri_in', 'p15pri_inm', 'p15pri_inf', 'p15pri_co', 'p15pri_com',
       'p15pri_cof', 'p15sec_in', 'p15sec_inm', 'p15sec_inf', 'p15sec_co',
       'p15sec_com', 'p15sec_cof', 'p18ym_pb', 'p18ym_pb_m', 'p18ym_pb_f',
       'p_0a14', 'p_0a14_m', 'p_0a14_f', 'p_15a24', 'p_15a24_m', 'p_15a24_f',
       'p_25a59', 'p_25a59_m', 'p_25a59_f', 'p_60ymas', 'p_60ymas_m',
       'p_60ymas_f', 'p15ym_an', 'hombres_dmt1_sin_esc',
       'hombres_dmt1_preescolar', 'hombres_dmt1_primaria',
       'hombres_dmt1_secundaria', 'hombres_dmt1_preparatoria',
       'hombres_dmt1_profesional', 'hombres_dmt1_posgrado',
       'hombres_dmt2_sin_esc', 'hombres_dmt2_preescolar',
       'hombres_dmt2_primaria', 'hombres_dmt2_secundaria',
       'hombres_dmt2_preparatoria', 'hombres_dmt2_profesional',
       'hombres_dmt2_posgrado', 'mujeres_dmt1_sin_esc',
       'mujeres_dmt1_preescolar', 'mujeres_dmt1_primaria',
       'mujeres_dmt1_secundaria', 'mujeres_dmt1_preparatoria',
       'mujeres_dmt1_profesional', 'mujeres_dmt1_posgrado',
       'mujeres_dmt2_sin_esc', 'mujeres_dmt2_preescolar',
       'mujeres_dmt2_primaria', 'mujeres_dmt2_secundaria',
       'mujeres_dmt2_preparatoria', 'mujeres_dmt2_profesional',
       'mujeres_dmt2_posgrado', 'dmt1_total', 'dmt2_total', 'otro_total',
       'dmt1_fem', 'dmt2_fem', 'dmt1_masc', 'dmt2_masc', '0-14_sexo1_dmt1',
       '0-14_sexo1_dmt2', '0-14_sexo2_dmt1', '0-14_sexo2_dmt2',
       '15-24_sexo1_dmt1', '15-24_sexo1_dmt2', '15-24_sexo2_dmt1',
       '15-24_sexo2_dmt2', '25-59_sexo1_dmt1', '25-59_sexo1_dmt2',
       '25-59_sexo2_dmt1', '25-59_sexo2_dmt2', '60+_sexo1_dmt1',
       '60+_sexo1_dmt2', '60+_sexo2_dmt1', '60+_sexo2_dmt2', 'casos totales'],
      dtype='object')

In [7]:
union

,año,clave_municipio,nom_mun,pobtot,pobmas,pobfem,p15ym_an_m,p15ym_an_f,p15ym_se,p15ym_se_m,...,15-24_sexo2_dmt2,25-59_sexo1_dmt1,25-59_sexo1_dmt2,25-59_sexo2_dmt1,25-59_sexo2_dmt2,60+_sexo1_dmt1,60+_sexo1_dmt2,60+_sexo2_dmt1,60+_sexo2_dmt2,casos totales
0,2015,0.0,Total de la entidad Ciudad de México,9030512.0,4319355.0,4711157.0,37010.0,86812.0,177434.0,64956.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,2.0,Azcapotzalco,423458.0,200502.0,222956.0,1146.0,3309.0,5987.0,1766.0,...,0.0,2.0,63.0,3.0,27.0,1.0,170.0,2.0,164.0,432.0
2,2015,3.0,Coyoacán,617432.0,290800.0,326631.0,1984.0,4615.0,9292.0,3102.0,...,0.0,2.0,56.0,2.0,24.0,6.0,182.0,3.0,226.0,501.0
3,2015,4.0,Cuajimalpa de Morelos,202038.0,96396.0,105643.0,908.0,1963.0,4113.0,1444.0,...,0.0,0.0,11.0,0.0,8.0,1.0,37.0,2.0,36.0,96.0
4,2015,5.0,Gustavo A. Madero,1179562.0,567554.0,612008.0,4934.0,12178.0,26228.0,10714.0,...,1.0,5.0,167.0,4.0,94.0,5.0,444.0,7.0,499.0,1227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2020,13.0,Xochimilco,442178.0,215452.0,226726.0,2395.0,4494.0,9064.0,3516.0,...,0.0,4.0,115.0,1.0,36.0,2.0,248.0,0.0,243.0,650.0
98,2020,14.0,Benito Juárez,434153.0,202121.0,232032.0,388.0,962.0,2153.0,672.0,...,0.0,3.0,23.0,1.0,11.0,0.0,133.0,0.0,129.0,300.0
99,2020,15.0,Cuauhtémoc,545884.0,260951.0,284933.0,1213.0,3179.0,6077.0,1903.0,...,0.0,0.0,100.0,4.0,58.0,3.0,311.0,1.0,296.0,775.0
100,2020,16.0,Miguel Hidalgo,414470.0,195467.0,219003.0,701.0,1897.0,3430.0,1008.0,...,0.0,2.0,53.0,3.0,29.0,1.0,167.0,2.0,169.0,426.0
101,2020,17.0,Venustiano Carranza,443704.0,210118.0,233586.0,1218.0,2737.0,5055.0,1679.0,...,0.0,4.0,108.0,2.0,49.0,1.0,276.0,2.0,306.0,748.0

In [8]:
union = pd.merge(union, pobreza_final, on=["año", "clave_municipio"], how="outer")
union.columns

Index(['año', 'clave_municipio', 'nom_mun', 'pobtot', 'pobmas', 'pobfem',
       'p15ym_an_m', 'p15ym_an_f', 'p15ym_se', 'p15ym_se_m', 'p15ym_se_f',
       'p15pri_in', 'p15pri_inm', 'p15pri_inf', 'p15pri_co', 'p15pri_com',
       'p15pri_cof', 'p15sec_in', 'p15sec_inm', 'p15sec_inf', 'p15sec_co',
       'p15sec_com', 'p15sec_cof', 'p18ym_pb', 'p18ym_pb_m', 'p18ym_pb_f',
       'p_0a14', 'p_0a14_m', 'p_0a14_f', 'p_15a24', 'p_15a24_m', 'p_15a24_f',
       'p_25a59', 'p_25a59_m', 'p_25a59_f', 'p_60ymas', 'p_60ymas_m',
       'p_60ymas_f', 'p15ym_an', 'hombres_dmt1_sin_esc',
       'hombres_dmt1_preescolar', 'hombres_dmt1_primaria',
       'hombres_dmt1_secundaria', 'hombres_dmt1_preparatoria',
       'hombres_dmt1_profesional', 'hombres_dmt1_posgrado',
       'hombres_dmt2_sin_esc', 'hombres_dmt2_preescolar',
       'hombres_dmt2_primaria', 'hombres_dmt2_secundaria',
       'hombres_dmt2_preparatoria', 'hombres_dmt2_profesional',
       'hombres_dmt2_posgrado', 'mujeres_dmt1_sin_esc',
       'mujeres_dmt1_preescolar', 'mujeres_dmt1_primaria',
       'mujeres_dmt1_secundaria', 'mujeres_dmt1_preparatoria',
       'mujeres_dmt1_profesional', 'mujeres_dmt1_posgrado',
       'mujeres_dmt2_sin_esc', 'mujeres_dmt2_preescolar',
       'mujeres_dmt2_primaria', 'mujeres_dmt2_secundaria',
       'mujeres_dmt2_preparatoria', 'mujeres_dmt2_profesional',
       'mujeres_dmt2_posgrado', 'dmt1_total', 'dmt2_total', 'otro_total',
       'dmt1_fem', 'dmt2_fem', 'dmt1_masc', 'dmt2_masc', '0-14_sexo1_dmt1',
       '0-14_sexo1_dmt2', '0-14_sexo2_dmt1', '0-14_sexo2_dmt2',
       '15-24_sexo1_dmt1', '15-24_sexo1_dmt2', '15-24_sexo2_dmt1',
       '15-24_sexo2_dmt2', '25-59_sexo1_dmt1', '25-59_sexo1_dmt2',
       '25-59_sexo2_dmt1', '25-59_sexo2_dmt2', '60+_sexo1_dmt1',
       '60+_sexo1_dmt2', '60+_sexo2_dmt1', '60+_sexo2_dmt2', 'casos totales',
       'municipio', 'pobreza_porcentaje', 'pobreza_poblacion',
       'pobreza_extrema_porcentaje', 'pobreza_extrema_poblacion',
       'pobreza_moderada_porcentaje', 'pobreza_moderada_poblacion'],
      dtype='object')

In [9]:
union

,año,clave_municipio,nom_mun,pobtot,pobmas,pobfem,p15ym_an_m,p15ym_an_f,p15ym_se,p15ym_se_m,...,60+_sexo2_dmt1,60+_sexo2_dmt2,casos totales,municipio,pobreza_porcentaje,pobreza_poblacion,pobreza_extrema_porcentaje,pobreza_extrema_poblacion,pobreza_moderada_porcentaje,pobreza_moderada_poblacion
0,2015,0.0,Total de la entidad Ciudad de México,9030512.0,4319355.0,4711157.0,37010.0,86812.0,177434.0,64956.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,2.0,Azcapotzalco,423458.0,200502.0,222956.0,1146.0,3309.0,5987.0,1766.0,...,2.0,164.0,432.0,Azcapotzalco,19.5,77859.0,0.5,2132.0,18.9,75727.0
2,2015,3.0,Coyoacán,617432.0,290800.0,326631.0,1984.0,4615.0,9292.0,3102.0,...,3.0,226.0,501.0,Coyoacán,19.8,113337.0,0.6,3345.0,19.2,109992.0
3,2015,4.0,Cuajimalpa de Morelos,202038.0,96396.0,105643.0,908.0,1963.0,4113.0,1444.0,...,2.0,36.0,96.0,Cuajimalpa de Morelos,30.1,55995.0,1.2,2194.0,29.0,53801.0
4,2015,5.0,Gustavo A. Madero,1179562.0,567554.0,612008.0,4934.0,12178.0,26228.0,10714.0,...,7.0,499.0,1227.0,Gustavo A. Madero,28.4,344966.0,1.1,13950.0,27.2,331016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2020,13.0,Xochimilco,442178.0,215452.0,226726.0,2395.0,4494.0,9064.0,3516.0,...,0.0,243.0,650.0,Xochimilco,48.2,210781.0,9.3,40693.0,38.9,170088.0
98,2020,14.0,Benito Juárez,434153.0,202121.0,232032.0,388.0,962.0,2153.0,672.0,...,0.0,129.0,300.0,Benito Juárez,7.9,29466.0,0.3,1167.0,7.6,28299.0
99,2020,15.0,Cuauhtémoc,545884.0,260951.0,284933.0,1213.0,3179.0,6077.0,1903.0,...,1.0,296.0,775.0,Cuauhtémoc,20.9,102753.0,2.5,12053.0,18.4,90700.0
100,2020,16.0,Miguel Hidalgo,414470.0,195467.0,219003.0,701.0,1897.0,3430.0,1008.0,...,2.0,169.0,426.0,Miguel Hidalgo,13.5,49100.0,0.9,3406.0,12.5,45695.0
101,2020,17.0,Venustiano Carranza,443704.0,210118.0,233586.0,1218.0,2737.0,5055.0,1679.0,...,2.0,306.0,748.0,Venustiano Carranza,30.0,124431.0,2.9,12066.0,27.1,112366.0

In [10]:
# 1. Identificamos las columnas que queremos sumar (todas menos las llaves)
columnas_datos = [col for col in union.columns if col not in ['año', 'clave_municipio', 'nom_mun', 'pobtot', 'pobmas', 'pobfem',
       'p15ym_an_m', 'p15ym_an_f', 'p15ym_se', 'p15ym_se_m', 'p15ym_se_f',
       'p15pri_in', 'p15pri_inm', 'p15pri_inf', 'p15pri_co', 'p15pri_com',
       'p15pri_cof', 'p15sec_in', 'p15sec_inm', 'p15sec_inf', 'p15sec_co',
       'p15sec_com', 'p15sec_cof', 'p18ym_pb', 'p18ym_pb_m', 'p18ym_pb_f',
       'p_0a14', 'p_0a14_m', 'p_0a14_f', 'p_15a24', 'p_15a24_m', 'p_15a24_f',
       'p_25a59', 'p_25a59_m' ]]

# 2. Creamos un DataFrame temporal con las sumas anuales
# Esto calcula el total de todas las alcaldías por año
totales_anuales = union.groupby('año')[columnas_datos].transform('sum')

# 3. Solo aplicamos esa suma a las filas que representan el "Total CDMX"
# Supongamos que la clave del total es '0'
es_fila_total = union['clave_municipio'] == 0 

# Llenamos solo en esas filas los valores calculados
union.loc[es_fila_total, columnas_datos] = totales_anuales[es_fila_total]

In [11]:

union = union.drop(columns=['municipio'])

In [12]:
union[union["año"] == 2015]

,año,clave_municipio,nom_mun,pobtot,pobmas,pobfem,p15ym_an_m,p15ym_an_f,p15ym_se,p15ym_se_m,...,60+_sexo1_dmt2,60+_sexo2_dmt1,60+_sexo2_dmt2,casos totales,pobreza_porcentaje,pobreza_poblacion,pobreza_extrema_porcentaje,pobreza_extrema_poblacion,pobreza_moderada_porcentaje,pobreza_moderada_poblacion
0,2015,0.0,Total de la entidad Ciudad de México,9030512.0,4319355.0,4711157.0,37010.0,86812.0,177434.0,64956.0,...,2720.0,44.0,3022.0,7614.0,422.3,2457084.0,17.0,105735.0,404.9,2351349.0
1,2015,2.0,Azcapotzalco,423458.0,200502.0,222956.0,1146.0,3309.0,5987.0,1766.0,...,170.0,2.0,164.0,432.0,19.5,77859.0,0.5,2132.0,18.9,75727.0
2,2015,3.0,Coyoacán,617432.0,290800.0,326631.0,1984.0,4615.0,9292.0,3102.0,...,182.0,3.0,226.0,501.0,19.8,113337.0,0.6,3345.0,19.2,109992.0
3,2015,4.0,Cuajimalpa de Morelos,202038.0,96396.0,105643.0,908.0,1963.0,4113.0,1444.0,...,37.0,2.0,36.0,96.0,30.1,55995.0,1.2,2194.0,29.0,53801.0
4,2015,5.0,Gustavo A. Madero,1179562.0,567554.0,612008.0,4934.0,12178.0,26228.0,10714.0,...,444.0,7.0,499.0,1227.0,28.4,344966.0,1.1,13950.0,27.2,331016.0
5,2015,6.0,Iztacalco,394510.0,187443.0,207068.0,1256.0,3303.0,6276.0,1972.0,...,161.0,2.0,183.0,448.0,17.1,61122.0,0.4,1441.0,16.7,59681.0
6,2015,7.0,Iztapalapa,1825636.0,884324.0,941312.0,9708.0,22332.0,46648.0,18950.0,...,507.0,7.0,571.0,1490.0,35.0,665408.0,1.7,32741.0,33.2,632668.0
7,2015,8.0,La Magdalena Contreras,243354.0,116390.0,126964.0,1322.0,2880.0,6558.0,2373.0,...,62.0,1.0,62.0,166.0,32.6,85716.0,1.3,3490.0,31.2,82225.0
8,2015,9.0,Milpa Alta,141634.0,69282.0,72352.0,1233.0,2242.0,3796.0,1460.0,...,47.0,0.0,53.0,136.0,49.2,76765.0,2.0,3063.0,47.2,73702.0
9,2015,10.0,Álvaro Obregón,743086.0,353524.0,389562.0,3174.0,7697.0,16115.0,5374.0,...,196.0,4.0,219.0,551.0,27.9,208689.0,1.1,8023.0,26.8,200666.0
10,2015,11.0,Tláhuac,376289.0,182700.0,193589.0,1828.0,3930.0,7367.0,2612.0,...,84.0,1.0,115.0,275.0,39.2,154855.0,1.3,5307.0,37.8,149548.0
11,2015,12.0,Tlalpan,675248.0,323508.0,351740.0,3196.0,6800.0,15032.0,5450.0,...,157.0,2.0,153.0,437.0,32.1,217122.0,1.8,12104.0,30.3,205017.0
12,2015,13.0,Xochimilco,428592.0,210378.0,218214.0,2562.0,5070.0,9472.0,3584.0,...,109.0,2.0,128.0,327.0,40.5,187111.0,2.4,11080.0,38.1,176031.0
13,2015,14.0,Benito Juárez,409796.0,189266.0,220530.0,374.0,1158.0,2498.0,722.0,...,93.0,2.0,116.0,258.0,5.0,16424.0,0.1,475.0,4.8,15949.0
14,2015,15.0,Cuauhtémoc,538858.0,256338.0,282520.0,1324.0,3829.0,7108.0,2085.0,...,204.0,5.0,202.0,530.0,16.0,74685.0,0.7,3155.0,15.4,71530.0
15,2015,16.0,Miguel Hidalgo,393680.0,184067.0,209612.0,755.0,2254.0,4780.0,1408.0,...,115.0,2.0,108.0,295.0,7.1,20367.0,0.1,370.0,7.0,19997.0
16,2015,17.0,Venustiano Carranza,437341.0,206884.0,230456.0,1306.0,3252.0,6166.0,1939.0,...,152.0,2.0,187.0,445.0,22.8,96663.0,0.7,2865.0,22.1,93799.0

In [13]:
# 1. Aseguramos que la máscara sea correcta
es_fila_total = union['clave_municipio'] == 0
columnas_porcentaje = ['pobreza_porcentaje', 'pobreza_extrema_porcentaje', 'pobreza_moderada_porcentaje']
columnas_poblacion = ['pobreza_poblacion', 'pobreza_extrema_poblacion', 'pobreza_moderada_poblacion']

# 2. Realizamos el cálculo usando .values para evitar errores de alineación
numerador = union.loc[es_fila_total, columnas_poblacion]
denominador = union.loc[es_fila_total, 'pobtot']

# Verificamos si el denominador no es cero para evitar errores
if (denominador != 0).all():
    # .values convierte el resultado en una matriz simple de números, 
    # quitando el problema de los índices de Pandas.
    union.loc[es_fila_total, columnas_porcentaje] = (numerador.div(denominador, axis=0) * 100).values
else:
    print("¡Cuidado! Tienes un cero en la población total de la fila seleccionada.")

In [14]:
union[union["año"] == 2015]

,año,clave_municipio,nom_mun,pobtot,pobmas,pobfem,p15ym_an_m,p15ym_an_f,p15ym_se,p15ym_se_m,...,60+_sexo1_dmt2,60+_sexo2_dmt1,60+_sexo2_dmt2,casos totales,pobreza_porcentaje,pobreza_poblacion,pobreza_extrema_porcentaje,pobreza_extrema_poblacion,pobreza_moderada_porcentaje,pobreza_moderada_poblacion
0,2015,0.0,Total de la entidad Ciudad de México,9030512.0,4319355.0,4711157.0,37010.0,86812.0,177434.0,64956.0,...,2720.0,44.0,3022.0,7614.0,27.20869,2457084.0,1.170864,105735.0,26.037826,2351349.0
1,2015,2.0,Azcapotzalco,423458.0,200502.0,222956.0,1146.0,3309.0,5987.0,1766.0,...,170.0,2.0,164.0,432.0,19.50000,77859.0,0.500000,2132.0,18.900000,75727.0
2,2015,3.0,Coyoacán,617432.0,290800.0,326631.0,1984.0,4615.0,9292.0,3102.0,...,182.0,3.0,226.0,501.0,19.80000,113337.0,0.600000,3345.0,19.200000,109992.0
3,2015,4.0,Cuajimalpa de Morelos,202038.0,96396.0,105643.0,908.0,1963.0,4113.0,1444.0,...,37.0,2.0,36.0,96.0,30.10000,55995.0,1.200000,2194.0,29.000000,53801.0
4,2015,5.0,Gustavo A. Madero,1179562.0,567554.0,612008.0,4934.0,12178.0,26228.0,10714.0,...,444.0,7.0,499.0,1227.0,28.40000,344966.0,1.100000,13950.0,27.200000,331016.0
5,2015,6.0,Iztacalco,394510.0,187443.0,207068.0,1256.0,3303.0,6276.0,1972.0,...,161.0,2.0,183.0,448.0,17.10000,61122.0,0.400000,1441.0,16.700000,59681.0
6,2015,7.0,Iztapalapa,1825636.0,884324.0,941312.0,9708.0,22332.0,46648.0,18950.0,...,507.0,7.0,571.0,1490.0,35.00000,665408.0,1.700000,32741.0,33.200000,632668.0
7,2015,8.0,La Magdalena Contreras,243354.0,116390.0,126964.0,1322.0,2880.0,6558.0,2373.0,...,62.0,1.0,62.0,166.0,32.60000,85716.0,1.300000,3490.0,31.200000,82225.0
8,2015,9.0,Milpa Alta,141634.0,69282.0,72352.0,1233.0,2242.0,3796.0,1460.0,...,47.0,0.0,53.0,136.0,49.20000,76765.0,2.000000,3063.0,47.200000,73702.0
9,2015,10.0,Álvaro Obregón,743086.0,353524.0,389562.0,3174.0,7697.0,16115.0,5374.0,...,196.0,4.0,219.0,551.0,27.90000,208689.0,1.100000,8023.0,26.800000,200666.0
10,2015,11.0,Tláhuac,376289.0,182700.0,193589.0,1828.0,3930.0,7367.0,2612.0,...,84.0,1.0,115.0,275.0,39.20000,154855.0,1.300000,5307.0,37.800000,149548.0
11,2015,12.0,Tlalpan,675248.0,323508.0,351740.0,3196.0,6800.0,15032.0,5450.0,...,157.0,2.0,153.0,437.0,32.10000,217122.0,1.800000,12104.0,30.300000,205017.0
12,2015,13.0,Xochimilco,428592.0,210378.0,218214.0,2562.0,5070.0,9472.0,3584.0,...,109.0,2.0,128.0,327.0,40.50000,187111.0,2.400000,11080.0,38.100000,176031.0
13,2015,14.0,Benito Juárez,409796.0,189266.0,220530.0,374.0,1158.0,2498.0,722.0,...,93.0,2.0,116.0,258.0,5.00000,16424.0,0.100000,475.0,4.800000,15949.0
14,2015,15.0,Cuauhtémoc,538858.0,256338.0,282520.0,1324.0,3829.0,7108.0,2085.0,...,204.0,5.0,202.0,530.0,16.00000,74685.0,0.700000,3155.0,15.400000,71530.0
15,2015,16.0,Miguel Hidalgo,393680.0,184067.0,209612.0,755.0,2254.0,4780.0,1408.0,...,115.0,2.0,108.0,295.0,7.10000,20367.0,0.100000,370.0,7.000000,19997.0
16,2015,17.0,Venustiano Carranza,437341.0,206884.0,230456.0,1306.0,3252.0,6166.0,1939.0,...,152.0,2.0,187.0,445.0,22.80000,96663.0,0.700000,2865.0,22.100000,93799.0

In [15]:
union.to_csv("df_final.csv", index=False, encoding="utf-8")
union.columns

Index(['año', 'clave_municipio', 'nom_mun', 'pobtot', 'pobmas', 'pobfem',
       'p15ym_an_m', 'p15ym_an_f', 'p15ym_se', 'p15ym_se_m', 'p15ym_se_f',
       'p15pri_in', 'p15pri_inm', 'p15pri_inf', 'p15pri_co', 'p15pri_com',
       'p15pri_cof', 'p15sec_in', 'p15sec_inm', 'p15sec_inf', 'p15sec_co',
       'p15sec_com', 'p15sec_cof', 'p18ym_pb', 'p18ym_pb_m', 'p18ym_pb_f',
       'p_0a14', 'p_0a14_m', 'p_0a14_f', 'p_15a24', 'p_15a24_m', 'p_15a24_f',
       'p_25a59', 'p_25a59_m', 'p_25a59_f', 'p_60ymas', 'p_60ymas_m',
       'p_60ymas_f', 'p15ym_an', 'hombres_dmt1_sin_esc',
       'hombres_dmt1_preescolar', 'hombres_dmt1_primaria',
       'hombres_dmt1_secundaria', 'hombres_dmt1_preparatoria',
       'hombres_dmt1_profesional', 'hombres_dmt1_posgrado',
       'hombres_dmt2_sin_esc', 'hombres_dmt2_preescolar',
       'hombres_dmt2_primaria', 'hombres_dmt2_secundaria',
       'hombres_dmt2_preparatoria', 'hombres_dmt2_profesional',
       'hombres_dmt2_posgrado', 'mujeres_dmt1_sin_esc',
       'mujeres_dmt1_preescolar', 'mujeres_dmt1_primaria',
       'mujeres_dmt1_secundaria', 'mujeres_dmt1_preparatoria',
       'mujeres_dmt1_profesional', 'mujeres_dmt1_posgrado',
       'mujeres_dmt2_sin_esc', 'mujeres_dmt2_preescolar',
       'mujeres_dmt2_primaria', 'mujeres_dmt2_secundaria',
       'mujeres_dmt2_preparatoria', 'mujeres_dmt2_profesional',
       'mujeres_dmt2_posgrado', 'dmt1_total', 'dmt2_total', 'otro_total',
       'dmt1_fem', 'dmt2_fem', 'dmt1_masc', 'dmt2_masc', '0-14_sexo1_dmt1',
       '0-14_sexo1_dmt2', '0-14_sexo2_dmt1', '0-14_sexo2_dmt2',
       '15-24_sexo1_dmt1', '15-24_sexo1_dmt2', '15-24_sexo2_dmt1',
       '15-24_sexo2_dmt2', '25-59_sexo1_dmt1', '25-59_sexo1_dmt2',
       '25-59_sexo2_dmt1', '25-59_sexo2_dmt2', '60+_sexo1_dmt1',
       '60+_sexo1_dmt2', '60+_sexo2_dmt1', '60+_sexo2_dmt2', 'casos totales',
       'pobreza_porcentaje', 'pobreza_poblacion', 'pobreza_extrema_porcentaje',
       'pobreza_extrema_poblacion', 'pobreza_moderada_porcentaje',
       'pobreza_moderada_poblacion'],
      dtype='object')

In [16]:
union = union[['año', 'clave_municipio', 'nom_mun', 'pobtot', 'pobmas', 'pobfem',
       'p15ym_an_m', 'p15ym_an_f', 'p15ym_se', 'p15ym_se_m', 'p15ym_se_f',
       'p15pri_in', 'p15pri_inm', 'p15pri_inf', 'p15pri_co', 'p15pri_com',
       'p15pri_cof', 'p15sec_in', 'p15sec_inm', 'p15sec_inf', 'p15sec_co',
       'p15sec_com', 'p15sec_cof', 'p18ym_pb', 'p18ym_pb_m', 'p18ym_pb_f',
       'p_0a14', 'p_0a14_m', 'p_0a14_f', 'p_15a24', 'p_15a24_m', 'p_15a24_f',
       'p_25a59', 'p_25a59_m', 'p_25a59_f', 'p_60ymas', 'p_60ymas_m',
       'p_60ymas_f', 'p15ym_an','pobreza_porcentaje', 'pobreza_poblacion', 'pobreza_extrema_porcentaje',
       'pobreza_extrema_poblacion', 'pobreza_moderada_porcentaje',
       'pobreza_moderada_poblacion']]

#union = union.rename(columns={'año': 'periodo'})
#union = union.rename(columns={'clave_municipio': 'id_alcaldia'})
#union = union.rename(columns={'nom_mun': 'nombre'})
#union = union.rename(columns={'pobtot': 'habitantes'})



#union.to_csv("df_final2.csv", index=False, encoding="utf-8")

In [17]:
union.to_csv("df_final2.csv", index=False, encoding="utf-8")